### PR TITLE
First bits of documentation for django-modeltranslation integration

### PR DESCRIPTION
**Pull request by Kniyl**
Got some time to write a quick overview for the django-modeltranslation integration. However, I need native english speakers to correct and improve the text.

### CODE REVIEW

**Comment by orotau** [comment]
Hi Mathias
I am happy to do that.
Can you just tell me the process to follow.
Cheers
Graham

**Comment by Kniyl** [comment]
Thank @orotau 

You can fork my repo and work from my modeltranslation-doc branch. If you make a pull request, it will show up here when I merge it.

Otherwise, you can send me a message with your modification and I’ll integrate them in my repo.

**Comment by rsadwick** [comment]
I'm sending over a PR - I did a pass on the spelling/grammar.  Feel free to use it and thanks for your work on translations.

**Comment by orotau** [comment]
ok I guess I don't need to do anything then. Very new to collaborating using github so treading carefully :-)

**Comment by stephenmcd** [comment]
Hi guys,

I'm merging this in now - I made a ton of tiny style tweaks, but generally left all the content intact as it is incredibly well done. Just wanted to say a huge thanks for going the extra mile and adding such great documentation, so thank you!

**Pull request merged**
