### PR TITLE
re-send class_prepared signal for self-referenced ForeignKeys

### PR DESCRIPTION
**Pull request by ZeroXn**
pr for issue #1395

### CODE REVIEW

**Comment by stephenmcd** [comment]
Can we add some comments explaining what the new lines do?

**Comment by ZeroXn** [comment]
in a new pr? or just add them here?
but as i mentioned in my initial issue, it not my code, and i linked to the source.
The way i understand how it works is like this
    if (extra_fields):
prevents the class_prepared being fired unnecessarily

    del fields[model_path]
removes an already processed field

    class_prepared.send(sender=sender)
process any remaining fields

**Comment by stephenmcd** [comment]
Re-sending `class_prepared` sounds wrong, wouldn't it potentially break other people's code if they relied on it only being sent once? Any thoughts @Kniyl ?

**Comment by AlexHill** [comment]
I refactored a bunch of code in this area for Django 1.9, and can confirm that referring to `"self"` works fine in 1.9 under Mezzanine's `1.9_compat` branch (see #1481).

I don't mind taking a look at this after that's merged if somebody needs it for 1.8, but probably not before then.

**Comment by stephenmcd** [comment]
I think having it fixed for 1.9 is good enough.

**Comment by jeffrand** [comment]
This feature would be extremely useful for me, and I'm not able to upgrade to 1.9 in the near term. @stephenmcd, would you reconsider merging this?

**Comment by stephenmcd** [comment]
@jeffrand your best bet would be to apply the change  to a fork of your own, and deploy against that.

**Pull request closed without merging**
