### PR TITLE
Update tinymce_setup.js: Django language codes

### PR DESCRIPTION
**Pull request by fygul**
https://docs.djangoproject.com/en/1.8/topics/i18n/
Language codes are generally represented in lower-case, but the HTTP Accept-Language header is case-insensitive. The separator is a dash.

I also noticed a warning message showing when I run 'python manage.py runserver'. it's about 'zh-tw' will be deprecated in Django 1.9, use 'zh-hant' instead. So I also add 'zh-hant'. I guess 'zh-cn' may be deprecated too.

I tested 'zh-hant' and 'zh-tw' well, my tinymce editor shows hints in Traditional Chinese now.

### CODE REVIEW

**Comment by stephenmcd** [comment]
Awesome, thanks a lot!

**Comment by stephenmcd** [comment]
What's your full name? I'll add it to the AUTHORS files.

Thanks again.

**Comment by fygul** [comment]
Fygul Hether
Thanks.
You also remind me to update my profile of github account. ;-)

**Comment by stephenmcd** [comment]
Great, thanks Fygul.

**Pull request merged**
