### PR TITLE
Translation in 3.1.10

### PR DESCRIPTION
**Pull request by dekomote**
Added support for modeltranslation in 3.1.10 tag.

### CODE REVIEW

**Comment by Kniyl** [comment]
Why would you want to push something that is already in master?

**Comment by dekomote** [comment]
This is based on the 3.1.10 tag. 3.1.10 is what's already on pypi and it doesn't support translations.
Some people are stuck on that version and can't upgrade to master (for instance - django < 1.7 constraint etc)

**Comment by dekomote** [comment]
Sorry, I didn't want to push it to master but a separate branch/tag.

**Comment by stephenmcd** [comment]
If you need something like this backported, you'll need to look at using your own fork and specify that in your requirements.

**Comment by dekomote** [comment]
Yup, I did exactly that. I just thought someone else might use it.

**Comment by stephenmcd** [comment]
For sure! Maybe you could post to the mailing list letting people know about your fork.

**Comment by dekomote** [comment]
Will do.

**Pull request closed without merging**
