### PR TITLE
Tighten up edge cases in password reset form

### PR DESCRIPTION
**Pull request by dsanders11**
There's three different cases being tightened up here.
1. Respect `ACCOUNTS_NO_USERNAME` and don't allow resetting by username if it's set to `True`.
2. If `username` evaluates to `False`, immediately return a `ValidationError` without a DB query. Some databases (such as MySQL) will take any number of blank spaces and return all rows with empty values. If accounts exist with no email address (created via admin) then a password reset request on ' ' will return all of those accounts from the DB and error due to too many results.
3. Handle legitimate multiple results. While username is unique, emails are not constrained to unique values. Manual entry in admin may lead to multiple accounts with the same email. Don't let the exception bubble up in this case and instead use a `ValidationError` to provide a better user experience.

### CODE REVIEW

**Comment by molokov** [comment]
Another thing I've noticed with some of my users is that for whatever reason, email address is case sensitive - so I've had people saying they can't reset their password by email address simply because they used an uppercase letter in their address when making an account, but not when trying to reset the password. Emails should be case insensitive.

**Comment by dsanders11** [comment]
@molokov, that's a good point, you're right, it looks like emails are indeed case sensitive on reset and what not. That's probably a separate pull request since the merits would need to be debated (technically emails have to be case sensitive but in the real world they rarely are) and it would need to be enforced throughout Mezzanine (user signup, updating email, etc).

**Comment by AlexHill** [comment]
I think it's fine in practise to consider emails completely case-insensitive for the purposes of uniqueness.

A good way to go here is to do what dabapps/django-email-as-username does IIRC – generate a username from a hash of the lowercased email address. That way you preserve the casing that the user entered, and still ensure uniqueness and case-insensitive lookups.

See here: https://github.com/dabapps/django-email-as-username/blob/master/emailusernames/utils.py#L15

**Comment by stephenmcd** [comment]
I'm not 100% sure this is right - I think `ACCOUNTS_NO_USERNAME` is meant to remove any support for usernames, but you may still want a username while being able to login via email.

Thoughts?

**Pull request closed without merging**
