### PR TITLE
Re-activate modeltranslation tabs for settings in admin

### PR DESCRIPTION
**Pull request by Kniyl**
They were gone in @2486606838c16464340ccf68a69ef421c0e6a3dd

### CODE REVIEW

**Comment by stephenmcd** [comment]
Strange, I think the intention there was that they'd show up via inheriting `BaseTranslationModelAdmin` - does that not work?

**Comment by Kniyl** [comment]
JQuery ui is not loading without explicitly adding it in the Media.

Plus there are two different js files for modeltranslation tabs. One for the pages and one for the settings.

**Comment by stephenmcd** [comment]
Ah I see now! So how about we do something with the `js` property, similar to what I did with the `css` property - copy its contents then modify it. That way if we need to change the base set of files we only do it in one spot.

What do you think?

**Comment by stephenmcd** [comment]
Something like this? 

```
    class Media(BaseTranslationModelAdmin.Media):
        css = copy(BaseTranslationModelAdmin.Media.css)
        css["all"] += ('mezzanine/css/admin/settings.css',)
        js = [js.replace("tabbed_translation_fields.js",
                         "tabbed_translation_settings.js")
              for js in BaseTranslationModelAdmin.Media.js]
```

**Comment by stephenmcd** [comment]
It's a bit hacky but at least we get some kind of re-use happening.

**Comment by Kniyl** [comment]
I was messing around with something like
```python
    js = copy(BaseTranslationModelAdmin.Media.js)
    if len(js):
        js = js[:2] + ("mezzanine/js/admin/tabbed_translation_settings.js",)
```
but it feels even worse.

**Comment by stephenmcd** [comment]
Yeah, it's a bit more fragile since it depends on the length + order.

I've got the above code working, I'll commit that. 

Sorry for breaking it!

**Comment by Kniyl** [comment]
No problem :)

**Comment by Kniyl** [comment]
Beware, though. I wasn't very consistent with files names.

It's ```tabbed_translatable_settings``` and not ```tabbed_translation_settings```

**Comment by stephenmcd** [comment]
Yeah I missed that at first then saw it when testing :-)

Here's my fix: f5ea57831bae8631e9a7216e9d2cf1bcff17da20

Thanks for picking this up.

**Pull request closed without merging**
