### PR TITLE
Add references to configuration.rst

### PR DESCRIPTION
**Pull request by chmelevskij**
Any mezzanine defined setting are referencing to configuration.rst

### CODE REVIEW

**Comment by stephenmcd** [comment]
Thank you! Couple of points:

Shouldn't `from string import ascii_letters` be `from string import ascii_letters as letters` ?

Is it necessary for the settings labels to be different from the settings? Eg do we have to use `SETTING-LABEL` instead of just `SETTING`? It would be much easier to read as text then. If it has to be different maybe it should be `REF-SETTING` which matches more closely what's happening.

**Comment by stephenmcd** [comment]
Oh I just saw the previous discussion where someone suggested the `-LABEL` suffix. I think adding `ref` is good but again if it's not necessary, we should just use ```:ref:`SETTING` ``` instead of ```:ref:`SETTING-LABEL` ```

**Comment by stephenmcd** [comment]
And once everything's done please squash into a single commit.

Thanks again!

**Comment by chmelevskij** [comment]
I've done the ```from string import ascii_letters as letters``` in the last commit. Will do other suggestions when by the end of the week when.

**Comment by stephenmcd** [comment]
Awesome, no rush :-)

**Pull request closed without merging**
