### PR TITLE
Compatibility with django >= 2.1

### PR DESCRIPTION
**Pull request by christianwgd**
- Django 2.1 removed the 'host' parameter from is_safe_url(), 'allowed_hosts' now is a required argument.
- As stated here https://github.com/django/django/pull/9938 in Django 2.1 the TOKEN_* constants were replaced by TokenType enums.

### CODE REVIEW

**Comment by christianwgd** [comment]
One thing more: I'm afraid i did't respect python2 compatibility for the inspect.getfullargspec call. Will add that...

**Comment by eht16** [comment]
Yay!
Though some of the commits rather look like spam and probably should be removed (just squash them away).

Together with https://github.com/stephenmcd/mezzanine/pull/1916 we should get a big step toward Django 2.2 support.

**Comment by eht16** [comment]
Just noticed: https://github.com/fermorltd/mezzanine/commit/f6da0a2219fa4d1b7bce4cac4e47d864dab08844 is also necessary.

**Comment by jerivas** [comment]
#1956 has been merged with support for Django >= 2.2

**Pull request closed without merging**
