### PR TITLE
Added more tests por pages

### PR DESCRIPTION
**Pull request by vindio**
Added more tests for mezzanine pages to increase code coverage.
Found a bug in models_for_pages (commented test fails with "PageAdmin.get_content_models() requires self argument")

### CODE REVIEW

**Comment by stephenmcd** [comment]
Thanks for this! Could you either remove the commented code or fix the issue with it?

**Comment by vindio** [comment]
Not sure about how to fix the bug so I removed the commented test

**Comment by vindio** [comment]
Not sure about how to fix the bug so I removed the commented test

**Comment by stephenmcd** [comment]
Thank you!

**Pull request merged**
