### PR TITLE
Show Links to Code in Package Documentation

### PR DESCRIPTION
**Pull request by prikhi**
Refs #1148

### CODE REVIEW

**Comment by stephenmcd** [comment]
Awesome, thanks so much!

**Comment by stephenmcd** [comment]
Merging this, but I can't actually see what affect it has - any idea?

**Comment by prikhi** [comment]
It adds the `[source]` links on the right here:
http://orotau-docs-mezzanine.readthedocs.org/en/latest/packages.html#module-mezzanine.generic

So you can quickly switch between the API docs & the implementation.

**Comment by prikhi** [comment]
And some day, I will add cross-references to the non-autodoc stuff, so from sections like [Keywords](http://orotau-docs-mezzanine.readthedocs.org/en/latest/utilities.html#keywords) you can reach the [keywords_for](http://orotau-docs-mezzanine.readthedocs.org/en/latest/packages.html#mezzanine.generic.templatetags.keyword_tags.keywords_for) autodoc, and then from the `[source]` links you can reach the actual code for the `keywords_for` function. All without leaving the comfort of you browser.

**Comment by stephenmcd** [comment]
Ah that's cool, when I built the docs locally I don't see that - I might need to update my version of sphinx, not sure.

Thanks

**Pull request merged**
