### PR TITLE
Fixed ADMIN_REMOVAL setting

### PR DESCRIPTION
**Pull request by tiktuk**
Fixed `lazy_registration()` as pr. @skabbit's comment in #1313.

### CODE REVIEW

**Comment by stephenmcd** [comment]
Thanks a lot. I think you moved (or didn't move) some comments in the code, and now they don't match the code they're commenting. Can you check that?

**Comment by tiktuk** [comment]
Should be fixed now :) .

**Comment by tiktuk** [comment]
I don't see why travis fails, it's not because of my fix, right?

**Comment by stephenmcd** [comment]
> I don't see why travis fails, it's not because of my fix, right?

I think it's unrelated. 

BTW I missed your last comments so forgot about this, sorry about that.

**Pull request merged**
