### PR TITLE
Fixes #1464 -- Django 1.9 compatibility [WIP]

### LINKED ISSUE #1464: Django 1.9 compatability
Hi, do you have any plans for support new django version?

### PR DESCRIPTION
**Pull request by AlexHill**
Minimum set of changes required to get Django to serve a page; not complete or correct yet.

### CODE REVIEW

**Comment by AlexHill** [comment]
This adds support for Django 1.9, and drops support for Django 1.7 and Python 3.3, in line with the versions supported by Django itself. Ping #1464.

Things to do:
- [ ] 1.9 drops `add_to_builtins` in favour of a keyword argument in the `TEMPLATES` setting, but 1.8 complains about an unknown keyword argument. So we need to somehow provide different default settings files for 1.9 and 1.8.
- [ ] Make sure removing `OrderableBase` is tested
- [ ] Make sure it's actually OK to remove `LazyAdminSite` in 1.9 (not at all sure of this)
- [ ] Update the syntax test to bring it into line with the standards applied to the Django codebase
- [ ] Kill all warnings where compatibility with 1.8 permits.
- [ ] Tidy up `set_dynamic_settings()`, especially w.r.t. template settings
- [ ] Possibly replace a lot of `set_dynamic_settings()` with the checks framework?

As to the last point, I'd quite like to move from automatically modifying settings to just raising warnings or errors, with specific instructions as to how to fix your settings file. I'm used to it now, but have run into lots of quite confusing problems in the past related to automatic reordering of `INSTALLED_APPS`, etc.

**Comment by stephenmcd** [comment]
> As to the last point, I'd quite like to move from automatically modifying settings to just raising warnings or errors, with specific instructions as to how to fix your settings file. I'm used to it now, but have run into lots of quite confusing problems in the past related to automatic reordering of INSTALLED_APPS, etc.

Agreed, will hopefully work toward silencing complaints we get about steering too far away from Django.

Thanks Alex.

**Comment by stephenmcd** [comment]
FYI I should have a good chunk of free time over the new year period - I'll try and test this out and finish it off if there's anything outstanding.

Thanks for all the effort Alex!

**Comment by stephenmcd** [comment]
Hey @AlexHill - thanks again for all the initial work! I've tested it and everything appears to be working now against 1.8 and 1.9. 

If you can give my changes a quick glance to make sure I haven't made any mistakes that'd be great, but regardless I'm gonna merge this now to give people a chance to start testing it. 

Note there are some minor accompanying changes in grappelli_safe and filebrowser_safe so dev versions of those should be used when testing.

**Pull request merged**
