### PR TITLE
Try and fix admin link error

### PR DESCRIPTION
**Pull request by petedermott**
Fix TinyMCE link issue referenced #1728 and #1594

### CODE REVIEW

**Comment by stephenmcd** [comment]
This was thought to be resolved and if so, you've presumably come across a similar yet different issue - there's no way of knowing though since you admittedly don't know what the cause is. Given that we can't just blindly accept a patch. Are you able to upload a minimal example with steps to reproduce the problem?

**Comment by stephenmcd** [comment]
BTW, I'll close this since it most likely isn't the correct fix. Once the real issue can be identified, then we can work out what the correct fix is.

**Comment by petedermott** [comment]
Understood. 

In hind sight more discussion and consistent replication of the issue probably would have been the better course of action, I just got over excited at finding a "fix".

I'm going to keep looking into this and will report my findings.

**Comment by stephenmcd** [comment]
I understand, I've done this plenty of times when contributing to others' projects, so don't sweat it.

I'm glad you'll keep looking into it - I would suggest creating a new project from scratch, and adding your code to it piece by piece until you can trigger the error, that way you'll have a minimal example you can upload and someone else can take a look at it from there.

**Pull request closed without merging**
