### PR TITLE
Updated the js in footer_scripts.html to handle universal analytics

### PR DESCRIPTION
**Pull request by avery-laird**
I realized the js is out of date with google's new universal analytics script, updated it to match with the new standard.

### CODE REVIEW

**Comment by stephenmcd** [comment]
Thanks Avery. 

You'll see in Cartridge that the old code (such as the `_gaq` variable) is leveraged in order to track the details of a completed purchase: https://github.com/stephenmcd/cartridge/blob/master/cartridge/shop/templates/shop/complete.html

Any idea what needs to happen there to use the newer code? We'll need to get that working before this can be merged.

Thanks again for your help.

**Comment by AlexHill** [comment]
There is a bit of an issue here in that you have to have your Analytics property transferred to universal analytics before you upgrade your tracking code.

From the [Universal Analytics Upgrade Centre](https://developers.google.com/analytics/devguides/collection/upgrade/guide):

> Data sent from one of the new tracking libraries and protocols will not be processed by a property that hasn't been transfered to Universal Analytics.

Google is transferring properties automatically now, but I don't think it's compete yet so some people will still be on classic.

Alex

**Comment by stephenmcd** [comment]
Thanks Alex.

Any idea if the old code will still work for accounts that have been transferred?

If so, I guess we can just keep the old code for now.

**Comment by AlexHill** [comment]
The transition is [currently in the third of four phases](https://developers.google.com/analytics/devguides/collection/upgrade/index#phases). All new properties are Universal and the remaining legacy properties are being transferred. Once that's done, the old code will be considered deprecated and we'll be able to safely upgrade.

**Comment by avery-laird** [comment]
Hi guys,

My bad, obviously I should have done a bit more homework! Glad you caught this before it became an issue.

**Comment by AlexHill** [comment]
Don't sweat it Avery, this is work that would have needed to be done at some point – now this PR can just be put on ice until it's needed. Good stuff.

**Comment by stephenmcd** [comment]
Yep no problem at all - definitely needed! Thanks Avery.

**Comment by stephenmcd** [comment]
We now have the updated tracking code for Cartridge in https://github.com/stephenmcd/cartridge/issues/224 - anyone know if it makes sense to upgrade this now? Another way of putting it, is it impossible for some people to use the new code?

**Comment by AlexHill** [comment]
> Universal Analytics is now the operating standard and all properties have been upgraded to Universal Analytics.

https://support.google.com/analytics/answer/4457764?hl=en

I've updated this patch at https://github.com/stephenmcd/mezzanine/tree/avery-laird-updated-google-UA to include mobile, and a `footer_js` block.

**Comment by AlexHill** [comment]
Corresponding change in Cartridge: https://github.com/stephenmcd/cartridge/tree/updated-google-GA

**Comment by AlexHill** [comment]
Closing this in favour of #1487. Thanks Avery.

**Pull request closed without merging**
