### PR TITLE
Use STATIC_URL to find window.__admin_media_prefix__

### PR DESCRIPTION
**Pull request by awartani**
Related to https://github.com/stephenmcd/mezzanine/issues/1805

### CODE REVIEW

**Comment by stephenmcd** [comment]
Presumably this breaks since `STATIC_URL` doesn't end with "/admin/"

**Comment by awartani** [comment]
@stephenmcd good catch, what if it was changed to `window.__admin_media_prefix__ = '{{ STATIC_URL }}/admin/';`

**Comment by stephenmcd** [comment]
I think the problem's with whatever staticfiles class you're using.

**Comment by awartani** [comment]
@stephenmcd I don't think so, the details are on https://github.com/stephenmcd/mezzanine/issues/1805 if you would like to see what's the issue.

Anyway, `'{% static "admin" %}/'`static is used to look up for a directory name, not a file and that where it crashed when it was linked to S3.

**Comment by stephenmcd** [comment]
What I mean is it works fine with the default staticfiles class, which indicates a problem with the one you're using.

**Comment by awartani** [comment]
@stephenmcd I don't think it's wise to think about it that way and to close the PR.

**Comment by ryneeverett** [comment]
@awartani If you demonstrated a clear understanding of the bug you're trying to fix you would probably be happier with the response. Stephen went with his intuitions because your technical arguments have been vague.

**Pull request closed without merging**
