### PR TITLE
Fix ValueError when importing blog posts from Blogger

### PR DESCRIPTION
**Pull request by dablak**
Fixed ValueError exception when parsing dates of imported Blogger posts. Issue #1483

### CODE REVIEW

**Comment by stephenmcd** [comment]
Since you've repeated the same code twice, how about putting it into a function and calling that from both spots?

**Comment by dablak** [comment]
Sure, good idea. There you go!

PS. It took me a few commits to have all the right line lengths and unnecessary spaces removed from the code. Very picky this mr. Travis hehehe

**Comment by stephenmcd** [comment]
Great, thanks. Can you also squash into a single commit with a proper commit message? I can merge it then.

**Comment by dablak** [comment]
There you go

**Comment by stephenmcd** [comment]
Absolutely perfect, thanks!

**Pull request merged**
