### PR TITLE
Test and fix for displayable_links_js

### PR DESCRIPTION
**Pull request by viaregio**
I think this is also related to issue #1514.

### CODE REVIEW

**Comment by stephenmcd** [comment]
Don't think this fix was quite right, I just committed what I think was more correct.

Thanks!

**Comment by molokov** [comment]
A related issue - the above commit does indeed fix the exception we were getting, and displayable_links now works when editing/inserting a link in TinyMCE from the 'front-end' editing.

However, I'm not getting the list of links when inserting/editing a link when editing a page/blog post through the Admin side of things - no exception thrown, but the list of links isn't appearing. 

Do you want me to raise this as a separate issue?

**Comment by jjmiranda** [comment]
@stephenmcd any more correct solution for isinstance() exception in  /displayable_links.js to commit in your master?
Thank you very much for your time on this.

**Comment by michela** [comment]
Popup link editor still broken in latest Mezzanine commit (43036df0ff8be70e44d5116ea467f01432867108). Noticed that the test wasn't merged from that pull  - this test hasn't been merged

+    def test_displayable_links(self):
+        self.client.login(username=self._username, password=self._password)
+        links_url = reverse('displayable_links_js')
+        response = self.client.get(links_url)
+        self.assertEqual(response.status_code, 200)

**Pull request closed without merging**
